<?php

namespace App\Observers;

use App\Models\Supplier;

class SupplierObserver
{
    public function created(Supplier $supplier)
    {
        // ext id is generated by the observer when a new supplier is created e.g ID: SUP-2023-001
        $supplier->ext_id = 'SUP-' . date('Y') . '-' . str_pad($supplier->id, 3, '0', STR_PAD_LEFT);
        $supplier->save();
    }

    public function updated(Supplier $supplier)
    {
        //
    }

    public function deleted(Supplier $supplier)
    {
        //
    }
}
